name: Build & Push Runtime Image

on:
  push:
    branches:
      - build

jobs:
  publish-runtime:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & push runtime image
        uses: docker/build-push-action@v4
        with:
          context: app
          file: Containerfile
          target: runtime
          platforms: linux/amd64,linux/arm64
          push: true
          tags: docker.io/pjfsu/go-hello-world-runtime:latest
